// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-YrJpjlxeD3k_knGHwHhaKdrKzBFmk_s',
    appId: '1:688753725231:web:593504e5c8fea1d60ddbda',
    messagingSenderId: '688753725231',
    projectId: 'ai-powered-pothole--reporting',
    authDomain: 'ai-powered-pothole--reporting.firebaseapp.com',
    storageBucket: 'ai-powered-pothole--reporting.firebasestorage.app',
    measurementId: 'G-GB9LTY6VNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wIniVGTTkEKK2IlXdEAAUaWw_lowhbk',
    appId: '1:688753725231:android:727d8fb1784d8be80ddbda',
    messagingSenderId: '688753725231',
    projectId: 'ai-powered-pothole--reporting',
    storageBucket: 'ai-powered-pothole--reporting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB32gyn5x9HZeZfNzeq_4zc4lTtpvP-qIU',
    appId: '1:688753725231:ios:bb743aae200a13ae0ddbda',
    messagingSenderId: '688753725231',
    projectId: 'ai-powered-pothole--reporting',
    storageBucket: 'ai-powered-pothole--reporting.firebasestorage.app',
    iosBundleId: 'com.example.roadwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB32gyn5x9HZeZfNzeq_4zc4lTtpvP-qIU',
    appId: '1:688753725231:ios:bb743aae200a13ae0ddbda',
    messagingSenderId: '688753725231',
    projectId: 'ai-powered-pothole--reporting',
    storageBucket: 'ai-powered-pothole--reporting.firebasestorage.app',
    iosBundleId: 'com.example.roadwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-YrJpjlxeD3k_knGHwHhaKdrKzBFmk_s',
    appId: '1:688753725231:web:614367dde34885800ddbda',
    messagingSenderId: '688753725231',
    projectId: 'ai-powered-pothole--reporting',
    authDomain: 'ai-powered-pothole--reporting.firebaseapp.com',
    storageBucket: 'ai-powered-pothole--reporting.firebasestorage.app',
    measurementId: 'G-10HVTK36SY',
  );
}
